module Absactualgrammar where

-- Haskell module generated by the BNF converter


newtype Ident = Ident String deriving (Eq,Ord,Show)
data Program =
   Programm Block
  deriving (Eq,Ord,Show)

data Block =
   Blockk [Stmt]
  deriving (Eq,Ord,Show)

data Stmt =
   Stmtt Exp
  deriving (Eq,Ord,Show)

data Exp =
   EAss Ident Exp
  deriving (Eq,Ord,Show)

